INSERT INTO PRODUCT_REVIEWS(ID,PROD_ID, RATING, REMARKS) VALUES (1,1,3,'Good One');
INSERT INTO PRODUCT_REVIEWS(ID,PROD_ID, RATING, REMARKS) VALUES (2,1,4,'Nice Prod');
INSERT INTO PRODUCT_REVIEWS(ID,PROD_ID, RATING, REMARKS) VALUES (3,1,5,'Very Good');